name: 'build'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run-script build
      - run: |
          npm pack
      - uses: actions/upload-artifact@v3
        with:
          name: npm-pack
          path: exchange-gcal-sync-*.tgz
